"""nullable owner email

Revision ID: 1607695a5697
Revises: 1d26dad81188
Create Date: 2025-06-12 16:46:07.389719

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1607695a5697"
down_revision: Union[str, None] = "1d26dad81188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_organization",
        "email",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "git_user", "email", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_user", "email", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "git_organization",
        "email",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
