"""commit, git_user and repository

Revision ID: 3413b2ebb106
Revises: 
Create Date: 2025-04-29 18:46:00.977167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3413b2ebb106'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_user',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('avatarUrl', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('login', sa.VARCHAR(length=255), nullable=False),
    sa.Column('oldId', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=False),
    sa.Column('defaultBranchName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('defaultBranchPrefix', sa.VARCHAR(length=255), nullable=False),
    sa.Column('isPrivate', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ownerId', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['git_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_ownerId'), 'repository', ['ownerId'], unique=False)
    op.create_table('commit',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('repositoryId', sa.VARCHAR(length=255), nullable=False),
    sa.Column('addition', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('deletion', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('authoredDate', sa.DATETIME(), nullable=False),
    sa.Column('authorAvatarUrl', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('authorEmail', sa.VARCHAR(length=255), nullable=False),
    sa.Column('authorId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('authorName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('committedDate', sa.DATETIME(), nullable=False),
    sa.Column('committerAvatarUrl', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('committerEmail', sa.VARCHAR(length=255), nullable=False),
    sa.Column('committerId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('committerName', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['git_user.id'], ),
    sa.ForeignKeyConstraint(['committerId'], ['git_user.id'], ),
    sa.ForeignKeyConstraint(['repositoryId'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_authorId'), 'commit', ['authorId'], unique=False)
    op.create_index(op.f('ix_commit_committerId'), 'commit', ['committerId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commit_committerId'), table_name='commit')
    op.drop_index(op.f('ix_commit_authorId'), table_name='commit')
    op.drop_table('commit')
    op.drop_index(op.f('ix_repository_ownerId'), table_name='repository')
    op.drop_table('repository')
    op.drop_table('git_user')
    # ### end Alembic commands ###
