"""allow no name users and org

Revision ID: 425c9bea6d8e
Revises: 1607695a5697
Create Date: 2025-06-17 15:33:14.664626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "425c9bea6d8e"
down_revision: Union[str, None] = "1607695a5697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_organization",
        "name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "git_user", "name", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_user", "name", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "git_organization",
        "name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
