"""change nullable on main branch

Revision ID: 55c854232c81
Revises: e587d727b603
Create Date: 2025-05-04 17:08:33.659644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "55c854232c81"
down_revision: Union[str, None] = "e587d727b603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "repository",
        "mainBranchName",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "repository",
        "mainBranchPrefix",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_constraint("repository_ibfk_1", "repository", type_="foreignkey")
    op.alter_column(
        "repository", "ownerId", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.create_foreign_key(
        "repository_ibfk_1", "repository", "owner", ["ownerId"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("repository_ibfk_1", "repository", type_="foreignkey")
    op.alter_column(
        "repository", "ownerId", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.create_foreign_key(
        "repository_ibfk_1", "repository", "owner", ["ownerId"], ["id"]
    )
    op.alter_column(
        "repository",
        "mainBranchPrefix",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "repository",
        "mainBranchName",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
