"""rename column for clarity

Revision ID: 8fb82f963a0a
Revises: b69ddb48dbd8
Create Date: 2025-05-11 14:24:56.239048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8fb82f963a0a"
down_revision: Union[str, None] = "b69ddb48dbd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repository",
        sa.Column(
            "rootCommitIsReached", sa.BOOLEAN(), server_default="0", nullable=False
        ),
    )
    op.drop_column("repository", "rootIsReached")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repository",
        sa.Column(
            "rootIsReached",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("repository", "rootCommitIsReached")
    # ### end Alembic commands ###
