"""update repository to track main branch and not default

Revision ID: e587d727b603
Revises: 3413b2ebb106
Create Date: 2025-05-04 16:54:15.676218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e587d727b603'
down_revision: Union[str, None] = '3413b2ebb106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('mainBranchName', sa.VARCHAR(length=255), nullable=False))
    op.add_column('repository', sa.Column('mainBranchPrefix', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('repository', 'defaultBranchName')
    op.drop_column('repository', 'defaultBranchPrefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('defaultBranchPrefix', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('repository', sa.Column('defaultBranchName', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('repository', 'mainBranchPrefix')
    op.drop_column('repository', 'mainBranchName')
    # ### end Alembic commands ###
