name: Migrate using Amazon ECS

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: bp-n-co/ecr-repo
  ECS_CLUSTER: BP-Cluster
  ECS_TASK_DEFINITION: migration-task:5

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: migration
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f docker/DockerfileAws -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run ECS migration task
        run: |
          aws ecs run-task \
            --cluster ${{ env.ECS_CLUSTER }} \
            --capacity-provider-strategy '[{"capacityProvider" : "capacity-provider"}]' \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --count 1 \
            --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.PRIVATE_SUBNET_ID }}],securityGroups=[${{ secrets.DB_SECURITY_GROUP_ID }}]}" \
            --overrides '{ 
              "containerOverrides": [ 
                { 
                  "name": "migration-container", 
                  "environment": [ 
                    { 
                      "name": "MYSQL_USER", 
                      "value": "${{ secrets.MYSQL_USERNAME_MIGRATION }}" 
                    }, 
                    { 
                      "name": "MYSQL_PASSWORD", 
                      "value": "${{ secrets.MYSQL_PASSWORD_MIGRATION }}" 
                    }, 
                    { 
                      "name": "MYSQL_HOST", 
                      "value": "${{ secrets.MYSQL_HOST }}" 
                    }, 
                    { 
                      "name": "MYSQL_PORT", 
                      "value": "3306" 
                    }, 
                    { 
                      "name": "MYSQL_DATABASE", 
                      "value": "bp_co" 
                    } 
                  ] 
                } 
              ], 
              "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecs-role" 
            }'
